use_frameworks!

platform :ios, '9.0'

target 'ModHookLibrary_Example' do
  pod 'ModHookLibrary', :path => '../'
  pod 'AFNetworking', '3.2.1'
  pod 'SDWebImage', '~> 5.0'
  pod 'Masonry', '1.1.0'
  pod 'YYModel', '1.0.4'
  pod 'SVGAPlayer', '~> 2.5'
  pod 'FLAnimatedImage', '~> 1.0'
  target 'ModHookLibrary_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
